Repository dyvenia/viadot, pull requests merged in 2024-06, with the labels that each got.

#916 Bugfix/saprfcv2 column shift
  src/viadot/sources/sap_rfc.py
Labels: bug, 2.0

#931 Sharepoint handle null values
  .github/workflows/ci-2.0.yml
  .vscode/settings.json
  CHANGELOG.md
  pyproject.toml
  src/viadot/sources/sharepoint.py
  tests/unit/test_file.xlsx
  tests/unit/test_sharepoint.py
Labels: bug, enhancement

#929 Add documentation for viadot 2.0 with new repository structure
  CONTRIBUTING.md
  docs/advanced_usage/docker_containers.md
  docs/getting_started/getting_started.md
  docs/howtos/config_file.md
  docs/howtos/howto_migrate_sources_tasks_and_flows.md
  docs/index.md
  docs/references/api_sources.md
  docs/references/orchestration/prefect/prefect_flows.md
  docs/references/orchestration/prefect/prefect_tasks.md
  docs/references/sources/api_sources.md
  docs/references/sources/sql_sources.md
  docs/references/sql_sources.md
  docs/tutorials/adding_source.md
  docs/tutorials/databricks.md
  docs/tutorials/supermetrics.md
  docs/user_guide/adding_prefect_flow.md
  docs/user_guide/adding_source.md
  docs/user_guide/config_key.md
  mkdocs.yml
  src/viadot/orchestration/__init__.py
  src/viadot/orchestration/prefect/flows/__init__.py
  src/viadot/orchestration/prefect/flows/cloud_for_customers_to_adls.py
  src/viadot/orchestration/prefect/flows/cloud_for_customers_to_databricks.py
  src/viadot/orchestration/prefect/flows/exchange_rates_to_adls.py
Labels: documentation, 2.0
