Repository dyvenia/viadot, pull requests merged in 2024-11, with the labels that each got.

#1093 ✨ Add DynamicDateHandler class
  src/viadot/orchestration/prefect/utils.py
  tests/unit/orchestration/prefect/test_utils.py
Labels: 2.0

#1103 Rye url change
  README.md
Labels: dependencies, 2.0

#1100 🐛 [BUGFIX] For `SAPRFCV2` adding whitespaces to match sub - queries
  .gitignore
  pyproject.toml
  requirements-dev.lock
  requirements.lock
  src/viadot/sources/sap_rfc.py
  tests/unit/test_sap_rfc_2.py
Labels: bug, 2.0

#1106 🔖 Version bump to 2.1.25
  pyproject.toml
Labels: 2.0

#1108 🔖 Version bump to 2.1.26
  pyproject.toml
Labels: 2.0
