Repository dyvenia/viadot, pull requests merged in 2024-10, with the labels that each got.

#1041 ✨ Add `Eurostat` source and Prefect tasks
  src/viadot/orchestration/prefect/flows/__init__.py
  src/viadot/orchestration/prefect/flows/eurostat_to_adls.py
  src/viadot/orchestration/prefect/tasks/__init__.py
  src/viadot/orchestration/prefect/tasks/eurostat.py
  src/viadot/sources/__init__.py
  src/viadot/sources/eurostat.py
  src/viadot/utils.py
  tests/integration/orchestration/prefect/flows/test_eurostat_to_adls.py
  tests/integration/orchestration/prefect/tasks/test_eurostat_to_df.py
  tests/unit/test_eurostat.py
  tests/unit/test_eurostat_response.json
Labels: 2.0

#1088 ✨ Insert getting password for `C4C` source
  src/viadot/sources/cloud_for_customers.py
Labels: bug, 2.0

#1092 ✨ Add `get_object_sizes` method to S3 source
  src/viadot/exceptions.py
  src/viadot/sources/s3.py
Labels: enhancement, 2.0

#1099 Remove `VidClub` connector
  CHANGELOG.md
  tests/integration/flows/test_vidclub_to_adls.py
  tests/integration/tasks/test_vid_club.py
  tests/integration/test_vid_club.py
  viadot/flows/__init__.py
  viadot/flows/vid_club_to_adls.py
  viadot/sources/__init__.py
  viadot/sources/vid_club.py
  viadot/tasks/__init__.py
  viadot/tasks/vid_club.py
Labels: enhancement
