Repository dyvenia/viadot, pull requests merged in 2024-09, with the labels that each got.

#1030 🐛Added if empty check to prevent not in index errors
  src/viadot/sources/sap_rfc.py
Labels: bug, 2.0

#1032 🔖 Version bump 2.1.18
  pyproject.toml
Labels: 2.0

#1033 ✨ Add `get_page_iterator()` method to `S3`
  src/viadot/sources/s3.py
Labels: enhancement, 2.0

#1042 🔖 Version bump 2.1.19
  pyproject.toml
Labels: 2.0

#1065 🐛 Fix whitespace removal causing duplicates in `SAPRFCV2`
  src/viadot/sources/sap_rfc.py
Labels: bug, 2.0
