Repository dyvenia/viadot, pull requests merged in 2025-04, with the labels that each got.

#1136 🐛 Changed parameter name from table_name to table
  src/viadot/orchestration/prefect/flows/sharepoint_list_to_redshift_spectrum.py
Labels: bug, 2.0

#1138 ✨ Add `describe_objects` function to S3 connector
  src/viadot/sources/s3.py
Labels: enhancement

#1140 🔖 Bump version to - 2.2.3
  pyproject.toml
Labels: 2.0

#1141 ✨ Update dbt_selects patterns with dbt build
  .secrets.baseline
  src/viadot/orchestration/prefect/flows/transform_and_catalog.py
Labels: enhancement, 2.0
